# Generated by Django 5.2 on 2025-05-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='session_id',
        ),
    ]
