# Generated by Django 5.2 on 2025-05-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_carrito_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='session_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
