# Generated by Django 5.2 on 2025-05-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carrito_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='imagen',
        ),
    ]
