# Generated by Django 5.2 on 2025-05-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_carritoproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
    ]
