# Generated by Django 5.2 on 2025-05-11 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_delete_carritoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito',
            name='imagen',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=160.0, max_digits=10),
            preserve_default=False,
        ),
    ]
