# Generated by Django 5.2 on 2025-05-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_carrito_fecha_creacion_carrito_imagen_carrito_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_creacion',
        ),
    ]
