# Generated by Django 5.2 on 2025-05-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_remove_carrito_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='imagen',
        ),
    ]
