# Generated by Django 5.2 on 2025-05-11 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0009_remove_carrito_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito',
            name='imagen',
            field=models.URLField(default='productos/imagen6.png'),
            preserve_default=False,
        ),
    ]
