# Generated by Django 5.2 on 2025-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0010_carrito_fecha_creacion_carrito_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
